# Generated by Django 4.0.5 on 2022-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0002_alter_alumno_options_alter_profesor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
